import { Inter } from "next/font/google";
import "./globals.css";
import {Roboto_Flex} from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// Set global font robot_flex

const roboto_flex = Roboto_Flex({
    weight: '300',
    subsets: ['latin'],
})

// Metadata for tab display
export const metadata = {
  title: "OtakuOasis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <html lang="en">
          <body className={roboto_flex.className + 'w-full'}>
          {children}
          </body>
        </html>
  );
}