export const options = {
        format: [
        {id: 1, label: "TV"},
        {id: 2, label: "Movie"},
        {id: 3, label: "OVA"},
        {id: 4, label: "Special"},
        {id: 5, label: "ONA"},
        {id: 6, label: "Music"},
        {id: 7, label: "CM"},
        {id: 8, label: "PV"},
        {id: 9, label: "TV_Special"},
        ],


        genre: [
        {id: 1, label: 'Action'},
        {id: 2, label: 'Adventure'},
        {id: 5, label: 'Avant Garde'},
        {id: 46, label: 'Award Winning'},
        {id: 28, label: 'Boys Love'},
        {id: 4, label: 'Comedy'},
        {id: 8, label: 'Drama'},
        {id: 10, label: 'Fantasy'},
        {id: 26, label: 'Girls Love'},
        {id: 47, label: 'Gourmet'},
        {id: 14, label: 'Horror'},
        {id: 7, label: 'Mystery'},
        {id: 22, label: 'Romance'},
        {id: 24, label: 'Sci-Fi'},
        {id: 36, label: 'Slice of Life'},
        {id: 30, label: 'Sports'},
        {id: 37, label: 'Supernatural'},
        {id: 41, label: 'Suspense'},
        {id: 50, label: 'Adult Cast'},
        {id: 51, label: 'Anthropomorphic'},
        {id: 52, label: 'CGDCT'},
        {id: 53, label: 'Childcare'},
        {id: 54, label: 'Combat Sports'},
        {id: 55, label: 'Delinquents'},
        {id: 39, label: 'Detective'},
        {id: 56, label: 'Educational'},
        {id: 57, label: 'Gag Humor'},
        {id: 58, label: 'Gore'},
        {id: 59, label: 'High Stakes Game'},
        {id: 13, label: 'Historical'},
        {id: 60, label: 'Idols (Female)'},
        {id: 61, label: 'Idols (Male)'},
        {id: 62, label: 'Isekai'},
        {id: 63, label: 'Iyashikei'},
        {id: 64, label: 'Love Polygon'},
        {id: 66, label: 'Mahou Shoujo'},
        {id: 17, label: 'Martial Arts'},
        {id: 18, label: 'Mecha'},
        {id: 67, label: 'Medical'},
        {id: 38, label: 'Military'},
        {id: 19, label: 'Music'},
        {id: 6, label: 'Mythology'},
        {id: 68, label: 'Organized Crime'},
        {id: 69, label: 'Otaku Culture'},
        {id: 20, label: 'Parody'},
        {id: 70, label: 'Performing Arts'},
        {id: 71, label: 'Pets'},
        {id: 40, label: 'Psychological'},
        {id: 3, label: 'Racing'},
        {id: 72, label: 'Reincarnation'},
        {id: 74, label: 'Romantic Subtext'},
        {id: 21, label: 'Samurai'},
        {id: 23, label: 'School'},
        {id: 75, label: 'Showbiz'},
        {id: 29, label: 'Space'},
        {id: 11, label: 'Strategy Game'},
        {id: 31, label: 'Super Power'},
        {id: 76, label: 'Survival'},
        {id: 77, label: 'Team Sports'},
        {id: 78, label: 'Time Travel'},
        {id: 32, label: 'Vampire'},
        {id: 79, label: 'Video Game'},
        {id: 80, label: 'Visual Arts'},
        {id: 48, label: 'Workplace'},
        {id: 43, label: 'Josei'},
        {id: 15, label: 'Kids'},
        {id: 42, label: 'Seinen'},
        {id: 25, label: 'Shoujo'},
        {id: 27, label: 'Shounen'},
    ],

        status: [
                {id:1, label: 'airing'},
                {id:2, label: 'complete'},
                {id:3, label: 'upcoming'}

        ],

        producer: [
                {id: 11, label: 'Madhouse'},
                {id: 4, label: 'Studio Bones'},
                {id: 2, label: 'Kyoto Animation'},
                {id: 858, label: 'Wit Studio'},
                {id: 18, label: 'Toei Animation'},
                {id: 569, label: 'MAPPA Studio'},
                {id: 21, label: 'Studio Ghibli'},
                {id: 14, label: 'Sunrise Studio'},
                {id: 56, label: 'A-1 Pictures'},
                {id: 43, label: 'Ufotable'},
                {id: 1, label: 'Studio Pierrot'},
                {id: 10, label: 'Production I.G'},
                {id: 803, label: 'Studio Trigger'},
                {id: 132, label: 'P.A.Works'},
                {id: 7, label: 'J.C.Staff'},
        ]

}